### PR TITLE
Add ventures page

### LINKED ISSUE #179: Ventures Page - Styling and Code
# Bounty
For Businesses to choose us they need to know how we can help them succeed. 

## Scope

- content has been worked out in this bounty: https://github.com/leapdao/leapdao-website/issues/163

## Deliverables

- convert content to style and code
- publish
- adjust navigation

## Roles
bounty gardener: @zschavi   / 10% 35 DAI
bounty worker: @mwaa 245 DAI
bounty reviewer: @Clearwood   / 20% 70 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

### LINKED ISSUE #186: Venture Onboarding Pipeline
# Bounty
Call To Actions (Demo & Schedule Call)  on ventures page need data collection forms
Collected data in forms are posted on Slack and Email sent to a leapdao biz email or vice versa

## Scope

- Two google forms one for demo and second for calls (Alternatives are welcomed)
- Add links to ventures page once the forms are available
- Information collected needs to trigger email or posted to slack channel. Might need to run Task on AWS
- Bare minimum information collected contact info, main topic of discussion and any more context message
- Create a private group on slack with all biz dev roles to act on data posted in channel
- Also follow up task what possible demos can be created

## Deliverables

- New Slack Channel
- Forms and Trigger task to Slack/Email

## Roles
bounty gardener: @mwaa / 40 DAI 
bounty worker:  @mwaa / 120 DAI
bounty reviewer: name / 40 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

### PR DESCRIPTION
**Pull request by mwaa**
Clone on local test functionality or test on https://test.leapdao.org/

- [ ] Npm install new packages
- [ ] Navigation changes still work no broken page links
- [ ] New page Ventures based on provided designs

Closes #179 Closes #186

### CODE REVIEW

**Comment by mwaa** [comment]
Follow up task on Call To Actions Available on #186

**Comment by Clearwood** [comment]
Great work, the alignment still feel a bit raw to me. Icons are different sizes across the page and paragraphs have different widths. 
image
The services part looks a bit too basic atm IMO. 
image
I also feel like we should stay to a consistent color scheme 
image
Also, does the slider change automatically or is it all manual?

**Comment by mwaa** [comment]
### Fixes
- Updated alignment of icons
- Consistent color code with rest of web pages
- Added url for contact form

### Answers to questions
- For the services without enough content for each not sure i can represent them in another way. Open to suggestions
- The Slider is on a 2 second timer and can also be controlled manually

**Comment by Clearwood** [comment]
thx for the update :rocket: , still some problems with vertical and center alignment 
image
image
image
Vertical align should definitely be fixed, logos are also of seemingly different sizes. E.g. peepCash and SunDAI.

**Comment by Clearwood** [comment]
and for the services part, think of great icons, e.g. what parity is doing:
image
also vertical alignment should be added for those cards as well.

**Comment by Clearwood** [comment]
@mwaa I think you could take what parity is doing for the service cards in general as inspiration, I think their layout makes a lot of sense and adding one sentence helps to grasp the essence. Please also increase their size and use a higher saturation for the background.

From the Our History Part in Our ventures please remove Deora and Peep.cash. Please use the blog article link for Volt Congress and SunDai and replace Dungeon Riches with Plasma Leap and link to the whitepaper.

**Review by Clearwood — APPROVED** [review]

**Pull request merged**
