### PR TITLE
feat: show Validate section as "Not available"

### PR DESCRIPTION
**Pull request by troggy**
Otherwise it may be misleading, as PoS is not available on Leap Network yet.

I'm not happy with proposed look and feel, appreciate help

### CODE REVIEW

**Comment by troggy** [comment]
[Preview](https://user-images.githubusercontent.com/163447/58588340-1e6a3f80-8268-11e9-8f57-fcbc40b81ede.png)

**Comment by sunify** [comment]
image

Too agressive IMO :-)

Maybe smth like that? Also, i think we still need CTA here, but just for contacting with us (not sure about button label)

**Comment by troggy** [comment]
Button label smth like "Let me know" ?

"Coming soon" is misleading as well. It is definitely not "soon" :)

**Comment by troggy** [comment]
Agree on CTA, created a separated issue: https://github.com/leapdao/leapdao-website/issues/81

Tried your suggestion for "coming soon"

**Comment by troggy** [comment]
[Preview 2](https://user-images.githubusercontent.com/163447/58629586-890d9080-82e5-11e9-8fc3-6ca461fea9f2.png)

**Pull request merged**
