### PR TITLE
feat: remove links for pages with outdated copy

### PR DESCRIPTION
**Pull request by troggy**
Requires #77 

~About~
~Resources~
+Whitepaper

image

### CODE REVIEW

**Comment by troggy** [comment]
@sunify what do you think?

**Comment by troggy** [comment]
🤷‍♂️

**Comment by sunify** [comment]
Wow, missed notification

**Comment by sunify** [comment]
~About~ 👍
~Resources~ 👍
+ Whitepaper 👎— we already have a link on page and it's not super important right now

**Comment by troggy** [comment]
> it's not super important right now

not sure about this. On the page, we are not talking ~enough~ at all about our unique proposition — provable computation on plasma

**Comment by articobandurini** [comment]
i'm not sure that we have to remove About page, as apparently this is the only source of information about us :) at least in this case we need to bring back those two columns on the top of the landing page proposed by me, which was removed by alex.

**Comment by sunify** [comment]
> not sure about this. On the page, we are not talking enough at all about our unique proposition — provable computation on plasma

Link in the menu won't help us with that

**Comment by sunify** [comment]
> i'm not sure that we have to remove About page, as apparently this is the only source of information about us :)

Well, according google analythics, we have 0 visits on this page for the last month 🤷‍♂️

**Comment by troggy** [comment]
> Link in the menu won't help us with that

Any backing behind such a strong opinion? I'd say you never know until you try and measure

**Comment by troggy** [comment]
@sunify I'm also interested about your opinion about our site in general? What is important right now and what would help us to outline provable computation feature — I sense you have opinions on that

**Comment by troggy** [comment]
stale

**Pull request closed without merging**
